Repository Jkim-Hack/cse3902, pull requests merged in 2021-04, with the labels that each got.

#225 Health HUD Positioning
  cse3902/Constants/HUDPositionConstants.cs
  cse3902/Content/UI/HealthUI.png
  cse3902/Entities/Link.cs
  cse3902/Entities/LinkStateMachine.cs
  cse3902/Game1.cs
  cse3902/HUD/HUDItems/HealthHUDItem.cs
  cse3902/HUD/HUDItems/MiniMapHUDItem.cs
  cse3902/Interfaces/IPlayer.cs
  cse3902/SpriteFactory/HUDSpriteFactory.cs
  cse3902/Sprites/HUD/HeartHUDSprite.cs
Labels: project task

#227 Map/compass & HUD layering
  cse3902/Constants/DimensionConstants.cs
  cse3902/Constants/MiniMapConstants.cs
  cse3902/Constants/OrangeMapConstants.cs
  cse3902/Content/Content.mgcb
  cse3902/Content/UI/map_compass_item.png
  cse3902/Content/UI/orange_map.png
  cse3902/Content/UI/orange_map_rooms.png
  cse3902/Game1.cs
  cse3902/HUD/HUDItems/CompassHUDItem.cs
  cse3902/HUD/HUDItems/MapCompassHUDItem.cs
  cse3902/HUD/HUDItems/MapHUDItem.cs
  cse3902/HUD/HUDItems/MiniMapHUDItem.cs
  cse3902/HUD/HUDItems/OrangeMapHUDItem.cs
  cse3902/HUD/HUDManager.cs
  cse3902/SpriteFactory/HUDSpriteFactory.cs
  cse3902/Utilities/HUDUtilities.cs
Labels: bug, code improvement, project task

#228 Trap fix
  cse3902/Collision/Collidables/PlayerCollidable.cs
  cse3902/Collision/Collidables/TrapCollidable.cs
  cse3902/Collision/CollisionManager.cs
  cse3902/Content/Content.mgcb
  cse3902/Content/trap.png
  cse3902/Entities/Enemies/Trap.cs
  cse3902/Game1.cs
  cse3902/Interfaces/ITrap.cs
  cse3902/Rooms/Room.cs
  cse3902/Rooms/RoomData/RoomTraps.cs
  cse3902/Rooms/RoomHandler.cs
  cse3902/SpriteFactory/EnemySpriteFactory.cs
  cse3902/Sprites/EnemySprites/TrapSprite.cs
  cse3902/XMLParsing/Room1.xml
  cse3902/XMLParsing/TrapParser.cs
  cse3902/XMLParsing/XMLParser.cs
Labels: additional function

#235 Camerapausestuff
  cse3902/Blocks/WalkableBlock.cs
  cse3902/Collision/Collidables/EnemyCollidable.cs
  cse3902/Collision/Collidables/PlayerCollidable.cs
  cse3902/Commands/ResetCommand.cs
  cse3902/Constants/LinkConstants.cs
  cse3902/Doors/NormalDownDoor.cs
  cse3902/Doors/NormalLeftDoor.cs
  cse3902/Doors/NormalRightDoor.cs
  cse3902/Doors/NormalUpDoor.cs
  cse3902/Entities/Enemies/Aquamentus.cs
  cse3902/Entities/Enemies/Gel.cs
  cse3902/Entities/Enemies/Goriya.cs
  cse3902/Entities/Enemies/Keese.cs
  cse3902/Entities/Enemies/Stalfos.cs
  cse3902/Entities/Enemies/Trap.cs
  cse3902/Entities/Enemies/WallMaster.cs
  cse3902/Entities/Link.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/Entities/LinkStateMachine.cs
  cse3902/Game1.cs
  cse3902/GameStateManager.cs
  cse3902/HUD/HUDItems/OrangeMapHUDItem.cs
  cse3902/Interfaces/ICondition.cs
  cse3902/Interfaces/IEntity.cs
  cse3902/Interfaces/IItem.cs
  cse3902/Interfaces/ITrap.cs
  cse3902/Items/BombItem.cs
  cse3902/Items/BoomerangItem.cs
  cse3902/Items/BowItem.cs
  cse3902/Items/ClockItem.cs
  cse3902/Items/CompassItem.cs
  cse3902/Items/FairyItem.cs
  cse3902/Items/HeartContainerItem.cs
  cse3902/Items/HeartItem.cs
  cse3902/Items/KeyItem.cs
  cse3902/Items/MapItem.cs
  cse3902/Items/RupeeItem.cs
  cse3902/Items/TriforceItem.cs
  cse3902/Rooms/Conditions/AllBlocksPushedOpenDoor.cs
  cse3902/Rooms/Conditions/AllBlocksPushedPlaySound.cs
  cse3902/Rooms/Conditions/AllEnemiesKilledBlocksPushable.cs
  cse3902/Rooms/Conditions/AllEnemiesKilledDropItem.cs
  cse3902/Rooms/Conditions/AllEnemiesKilledOpenDoor.cs
  cse3902/Rooms/Room.cs
  cse3902/Rooms/RoomData/RoomConditions.cs
  cse3902/Rooms/RoomHandler.cs
  cse3902/Rooms/RoomTransitionManager.cs
  cse3902/Sounds/SoundFactory.cs
  cse3902/SpriteFactory/ItemSpriteFactory.cs
  cse3902/XMLParsing/ConditionParser.cs
  cse3902/XMLParsing/EnemyParser.cs
  cse3902/XMLParsing/ItemParser.cs
  cse3902/XMLParsing/Room1.xml
  cse3902/XMLParsing/XMLParser.cs
Labels: additional function, bug, project task

#237 Orange map
  cse3902/Constants/DimensionConstants.cs
  cse3902/Game1.cs
  cse3902/HUD/HUDItems/MapCompassHUDItem.cs
  cse3902/HUD/HUDItems/MiniMapHUDItem.cs
  cse3902/HUD/HUDItems/OrangeMapHUDItem.cs
Labels: bug, project task

#238 Link death animation
  cse3902/Commands/LinkMovementCommand.cs
  cse3902/Constants/LinkConstants.cs
  cse3902/Content/Content.mgcb
  cse3902/Content/LinkDeath.png
  cse3902/Entities/DamageMasks/DamageMaskHandler.cs
  cse3902/Entities/DamageMasks/SingleMaskHandler.cs
  cse3902/Entities/Link.cs
  cse3902/Entities/LinkStateMachine.cs
  cse3902/Sprites/LinkSprite.cs
Labels: project task

#239 Fix link's heart reset after death
  cse3902/Entities/Link.cs
  cse3902/Entities/LinkStateMachine.cs
Labels: bug

#240 Hud health disappear
  cse3902/Collision/Collidables/PlayerCollidable.cs
  cse3902/HUD/HUDItems/HealthHUDItem.cs
  cse3902/Sprites/HUD/HeartHUDSprite.cs
  cse3902/Utilities/HUDUtilities.cs
Labels: bug

#244 changed stuff
  cse3902/Collision/Collidables/PlayerCollidable.cs
  cse3902/Constants/HeartConstants.cs
  cse3902/Entities/Enemies/Aquamentus.cs
  cse3902/Entities/Enemies/Gel.cs
  cse3902/Entities/Enemies/Goriya.cs
  cse3902/Entities/Enemies/Keese.cs
  cse3902/Entities/Enemies/Stalfos.cs
  cse3902/Entities/Enemies/Trap.cs
  cse3902/Entities/Enemies/WallMaster.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/Projectiles/BoomerangProjectile.cs
  cse3902/Projectiles/Fireball.cs
Labels: additional function, bug, code improvement

#251 Win animation & sounds
  cse3902/Constants/LinkConstants.cs
  cse3902/Content/Content.mgcb
  cse3902/Content/LOZ_Boss_Defeat.wav
  cse3902/Content/LOZ_Boss_Hurt.wav
  cse3902/Content/LOZ_Triforce.wav
  cse3902/Entities/Enemies/Aquamentus.cs
  cse3902/Entities/Link.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/Entities/LinkStateMachine.cs
  cse3902/HUD/HUDItems/MiniMapHUDItem.cs
  cse3902/HUD/HUDItems/OrangeMapHUDItem.cs
  cse3902/Items/TriforceItem.cs
  cse3902/Sounds/SoundFactory.cs
  cse3902/SpriteFactory/HUDSpriteFactory.cs
  cse3902/Sprites/HUD/HeartHUDSprite.cs
  cse3902/Sprites/LinkSprite.cs
  cse3902/Sprites/SpriteUtilities.cs
Labels: code improvement, project task

#252 Hud inventory
  cse3902/Constants/HUDPositionConstants.cs
  cse3902/Content/.Content.mgcb.swp
  cse3902/Content/Content.mgcb
  cse3902/Content/UI/Cursor.png
  cse3902/Content/UI/Inventory.png
  cse3902/Entities/Link.cs
  cse3902/Game1.cs
  cse3902/HUD/HUDItems/InventoryHUDItem.cs
  cse3902/HUD/HUDManager.cs
  cse3902/HUD/InventoryManager.cs
  cse3902/Items/ArrowItem.cs
  cse3902/SpriteFactory/HUDSpriteFactory.cs
  cse3902/SpriteFactory/ItemSpriteFactory.cs
  cse3902/Utilities/HUDUtilities.cs
Labels: project task

#253 Death animation effects
  cse3902/Entities/LinkStateMachine.cs
  cse3902/Sprites/LinkSprite.cs
  cse3902/Sprites/SpriteUtilities.cs
Labels: additional function

#254 Camerapausestuff
  cse3902/Commands/LinkMovementCommand.cs
  cse3902/Constants/LinkConstants.cs
  cse3902/Entities/Enemies/Aquamentus.cs
  cse3902/Entities/Enemies/Gel.cs
  cse3902/Entities/Enemies/Goriya.cs
  cse3902/Entities/Enemies/Keese.cs
  cse3902/Entities/Enemies/Stalfos.cs
  cse3902/Entities/Enemies/WallMaster.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/Entities/LinkStateMachine.cs
  cse3902/GameStateManager.cs
  cse3902/HUD/HUDItems/InventoryHUDItem.cs
  cse3902/HUD/HUDItems/MapCompassHUDItem.cs
  cse3902/HUD/HUDManager.cs
  cse3902/XMLParsing/EnemyParser.cs
Labels: additional function, bug, code improvement

#257 Camerapausestuff
  cse3902/Commands/CommandList.cs
  cse3902/Commands/LinkAttackItemCommand.cs
  cse3902/Commands/LinkSwordAttackCommand.cs
  cse3902/Commands/LinkUseItemCommand.cs
  cse3902/Entities/Link.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/Entities/LinkStateMachine.cs
  cse3902/Sprites/LinkSprite.cs
  cse3902/cse3902.csproj
Labels: additional function, bug

#258 Fix HUD inventory selection
  cse3902/Game1.cs
  cse3902/HUD/HUDItems/InventoryHUDItem.cs
Labels: bug

#259 Add item disappear on 0 value and remove collision manager
  cse3902/Game1.cs
  cse3902/HUD/HUDItems/InventoryHUDItem.cs
Labels: bug

#264 Camerapausestuff
  cse3902/Commands/ChangeHealthCommand.cs
  cse3902/Commands/ClearEnemiesCommand.cs
  cse3902/Commands/CommandList.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/Entities/LinkStateMachine.cs
  cse3902/HUD/HUDItems/InventoryHUDItem.cs
  cse3902/HUD/InventoryManager.cs
  cse3902/Rooms/RoomData/RoomEnemies.cs
  cse3902/SpriteFactory/ItemSpriteFactory.cs
  cse3902/XMLParsing/Room1.xml
Labels: additional function, bug

#284 Particle engine
  cse3902/Constants/ParticleConstants.cs
  cse3902/Content/Content.mgcb
  cse3902/Content/particles/circle.png
  cse3902/Content/particles/cloud.png
  cse3902/Content/particles/diamond.png
  cse3902/Content/particles/ring.png
  cse3902/Content/particles/star.png
  cse3902/Game1.cs
  cse3902/Interfaces/IParticle.cs
  cse3902/Interfaces/IParticleEmitter.cs
  cse3902/ParticleSystem/Emitters/ArrowEmitter.cs
  cse3902/ParticleSystem/Emitters/SwordEmitter.cs
  cse3902/ParticleSystem/ParticleEngine.cs
  cse3902/ParticleSystem/Particles/StraightMovingParticle.cs
  cse3902/Projectiles/ArrowProjectile.cs
  cse3902/Projectiles/SwordProjectile.cs
Labels: project task

#296 fixed bug where link wouldn't die when grabbed by wall master at half…
  cse3902/Collision/Collidables/PlayerCollidable.cs
  cse3902/Rooms/Conditions/RickRollRoom.cs
  cse3902/SpriteFactory/NPCSpriteFactory.cs
  cse3902/Sprites/NPCSprite.cs
  cse3902/Sprites/SpriteUtilities.cs
Labels: bug

#297 added vision block room condition and candle to inventory manager
  cse3902/HUD/InventoryManager.cs
  cse3902/Rooms/Conditions/VisionBlockCondition.cs
  cse3902/XMLParsing/ConditionParser.cs
Labels: additional function

#301 Settings
  cse3902/Commands/ResetCommand.cs
  cse3902/Doors/PortalDown.cs
  cse3902/Doors/PortalUp.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/Entities/LinkStateMachine.cs
  cse3902/Game1.cs
  cse3902/GameStateManager.cs
  cse3902/HUD/HUDItems/HealthHUDItem.cs
  cse3902/ParticleSystem/Particles/StraightMovingParticle.cs
  cse3902/Rooms/RoomData/RoomProjectiles.cs
  cse3902/Rooms/RoomHandler.cs
  cse3902/Rooms/RoomUtilities.cs
  cse3902/Sounds/SoundFactory.cs
  cse3902/Sprites/LinkSprite.cs
  cse3902/Sprites/SpriteUtilities.cs
  cse3902/XMLParsing/DoorParser.cs
  cse3902/cse3902.csproj
Labels: additional function, bug, code improvement

#310 Horde
  cse3902/Interfaces/ISpawner.cs
  cse3902/Rooms/Room.cs
  cse3902/Rooms/RoomData/RoomSpawners.cs
  cse3902/Rooms/RoomHandler.cs
  cse3902/Spawners/GelSpawner.cs
  cse3902/Spawners/GoryiaSpawner.cs
  cse3902/Spawners/KeeseSpawner.cs
  cse3902/Spawners/StalfosSpawner.cs
  cse3902/XMLParsing/SpawnerParser.cs
  cse3902/XMLParsing/XMLParser.cs
  cse3902/cse3902.csproj
Labels: project task

#322 Link inventory
  cse3902/Collision/Collidables/EnemyCollidable.cs
  cse3902/Constants/DamageConstants.cs
  cse3902/Constants/HUDPositionConstants.cs
  cse3902/Constants/ItemConstants.cs
  cse3902/Constants/SoundConstants.cs
  cse3902/Content/BluePotion.png
  cse3902/Content/BlueRing.png
  cse3902/Content/Content.mgcb
  cse3902/Content/MagicRodProjectile.png
  cse3902/Content/SwordItems.png
  cse3902/Content/UI/HUDInventoryItems.png
  cse3902/Content/dungeonMask.png
  cse3902/Entities/LinkInventory.cs
  cse3902/Entities/LinkStateMachine.cs
  cse3902/HUD/HUDItems/CurrentItemsHUDItem.cs
  cse3902/HUD/HUDItems/InventoryHUDItem.cs
  cse3902/HUD/InventoryManager.cs
  cse3902/Items/BluePotionItem.cs
  cse3902/Items/BlueRingItem.cs
  cse3902/Items/SwordItem.cs
  cse3902/Projectiles/BoomerangProjectile.cs
  cse3902/Projectiles/MagicBeamProjectile.cs
  cse3902/Projectiles/ProjectileHandler.cs
  cse3902/Rooms/Conditions/VisionBlockCondition.cs
  cse3902/Rooms/RoomData/RoomItems.cs
  cse3902/SpriteFactory/HUDSpriteFactory.cs
  cse3902/SpriteFactory/ItemSpriteFactory.cs
  cse3902/Sprites/HUD/InventoryItemSprite.cs
  cse3902/Utilities/HUDUtilities.cs
  cse3902/Utilities/InventoryUtilities.cs
  cse3902/XMLParsing/ItemParser.cs
  cse3902/XMLParsing/Level1.xml
  cse3902/cse3902.csproj
Labels: additional function, bug, code improvement

#324 Settings
  cse3902/Commands/BuyArrowsCommand.cs
  cse3902/Commands/ChangeHealthCommand.cs
  cse3902/Commands/ChangeRoomXYCommand.cs
  cse3902/Commands/ChangeRoomZCommand.cs
  cse3902/Commands/LinkAttackItemCommand.cs
  cse3902/Commands/LinkChangeWeapon.cs
  cse3902/Commands/LinkMovementCommand.cs
  cse3902/Commands/MoveCameraCommand.cs
  cse3902/Commands/PauseCommand.cs
  cse3902/Commands/UpdateSettingCommand.cs
  cse3902/Constants/CommandConstants.cs
  cse3902/Constants/DamageConstants.cs
  cse3902/Constants/DimensionConstants.cs
  cse3902/Constants/LinkConstants.cs
  cse3902/Constants/MovementConstants.cs
  cse3902/Constants/SpriteConstants.cs
  cse3902/Doors/DownStaircaseDoor.cs
  cse3902/Doors/NormalDownDoor.cs
  cse3902/Doors/NormalLeftDoor.cs
  cse3902/Doors/NormalRightDoor.cs
  cse3902/Doors/NormalUpDoor.cs
  cse3902/Doors/OffscreenUpDoor.cs
  cse3902/Doors/PortalDown.cs
  cse3902/Doors/PortalUp.cs
  cse3902/Entities/Enemies/BoggusBoss.cs
  cse3902/Entities/Enemies/Dodongo.cs
  cse3902/Entities/Enemies/Goriya.cs
  cse3902/Entities/Enemies/MarioBoss.cs
  cse3902/Entities/Enemies/Rope.cs
  cse3902/Entities/Enemies/Zol.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/NPCs/OldManNPC.cs
  cse3902/Projectiles/Fireball.cs
  cse3902/Rooms/Conditions/HordeRoomOpenDoor.cs
  cse3902/Rooms/RoomData/RoomSpawners.cs
  cse3902/Rooms/RoomHandler.cs
  cse3902/Settings/SettingsValues.cs
  cse3902/Spawners/GelSpawner.cs
  cse3902/Spawners/GoryiaSpawner.cs
  cse3902/Spawners/KeeseSpawner.cs
  cse3902/Spawners/StalfosSpawner.cs
  cse3902/SpriteFactory/EnemySpriteFactory.cs
  cse3902/Utilities/InventoryUtilities.cs
  cse3902/XMLParsing/ConditionParser.cs
  cse3902/XMLParsing/DoorParser.cs
  cse3902/XMLParsing/Level1.xml
  cse3902/XMLParsing/Level2.xml
  cse3902/XMLParsing/Level4.xml
  cse3902/XMLParsing/SpawnerParser.cs
  cse3902/XMLParsing/XMLParser.cs
Labels: additional function, bug, code improvement

#326 fixed bug where hearts would disappear when link dies with max health…
  cse3902/HUD/HUDItems/HealthHUDItem.cs
  cse3902/XMLParsing/Level2.xml
Labels: bug

#327 Link refractor
  cse3902/Entities/LinkStateMachine.cs
Labels: code improvement

#331 Add LinkEffectsManager for all texture changes/effects for link
  cse3902/Sprites/LinkEffectsManager.cs
  cse3902/Sprites/LinkSprite.cs
Labels: code improvement

#334 Settings
  cse3902/Commands/BuyArrowsCommand.cs
  cse3902/Commands/CommandList.cs
  cse3902/Commands/HitboxCommand.cs
  cse3902/Commands/LinkChangeWeapon.cs
  cse3902/Constants/CommandConstants.cs
  cse3902/Constants/DamageConstants.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/Game1.cs
  cse3902/GameStateManager.cs
  cse3902/HUD/InventoryManager.cs
  cse3902/Rooms/RoomData/RoomProjectiles.cs
  cse3902/Settings/SettingsValues.cs
  cse3902/Sprites/LinkEffectsManager.cs
  cse3902/Sprites/LinkSprite.cs
  cse3902/Utilities/InventoryUtilities.cs
  cse3902/XMLParsing/Level1.xml
  readme.md
  readme.txt
Labels: additional function, bug, code improvement

#335 Orange map & particle stuff
  cse3902/Constants/ParticleConstants.cs
  cse3902/HUD/HUDItems/OrangeMapHUDItem.cs
  cse3902/Projectiles/MagicBeamProjectile.cs
  cse3902/Projectiles/SwordProjectile.cs
Labels: bug

#338 Settings
  cse3902/HUD/InventoryManager.cs
  cse3902/Settings/SettingsValues.cs
  cse3902/Spawners/GelSpawner.cs
  cse3902/Spawners/GoryiaSpawner.cs
  cse3902/Spawners/KeeseSpawner.cs
  cse3902/Spawners/StalfosSpawner.cs
  cse3902/XMLParsing/Level1.xml
  cse3902/XMLParsing/Level4.xml
Labels: additional function

#347 Settings
  cse3902/Constants/ItemConstants.cs
  cse3902/Constants/MovementConstants.cs
  cse3902/Entities/AquamentusStateMachine.cs
  cse3902/Entities/Enemies/Aquamentus.cs
  cse3902/Entities/Enemies/BoggusBoss.cs
  cse3902/Entities/Enemies/BoggusBossStateMachine.cs
  cse3902/Entities/Enemies/MarioBoss.cs
  cse3902/Entities/Enemies/MarioBossStateMachine.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/ParticleSystem/Particles/SinusoidalMovingParticle.cs
  cse3902/Projectiles/BoomerangProjectile.cs
  cse3902/Rooms/Conditions/AllEnemiesKilledDropItem.cs
  cse3902/Settings/SettingsManager.cs
  cse3902/SpriteFactory/ItemSpriteFactory.cs
  cse3902/XMLParsing/Level2.xml
  cse3902/XMLParsing/Level3.xml
  readme.md
  readme.txt
Labels: additional function

#348 Settings
  cse3902/Collision/Collidables/EnemyCollidable.cs
  cse3902/Collision/Collidables/PlayerCollidable.cs
  cse3902/Collision/Collidables/ProjectileCollidable.cs
  cse3902/Constants/DamageConstants.cs
  cse3902/Constants/ItemConstants.cs
  cse3902/Entities/Enemies/Aquamentus.cs
  cse3902/Entities/Enemies/BoggusBoss.cs
  cse3902/Entities/Enemies/Dodongo.cs
  cse3902/Entities/Enemies/Gel.cs
  cse3902/Entities/Enemies/Goriya.cs
  cse3902/Entities/Enemies/Keese.cs
  cse3902/Entities/Enemies/MarioBoss.cs
  cse3902/Entities/Enemies/Rope.cs
  cse3902/Entities/Enemies/Stalfos.cs
  cse3902/Entities/Enemies/WallMaster.cs
  cse3902/Entities/Enemies/Zol.cs
  cse3902/Entities/Link.cs
  cse3902/Entities/LinkInventory.cs
  cse3902/Game1.cs
  cse3902/Interfaces/IEntity.cs
  cse3902/Projectiles/ArrowProjectile.cs
  cse3902/Projectiles/BombProjectile.cs
  cse3902/Projectiles/BoomerangProjectile.cs
  cse3902/Projectiles/EnemyBoomerangProjectile.cs
  cse3902/Projectiles/Fireball.cs
  cse3902/Projectiles/MagicBeamProjectile.cs
  cse3902/Projectiles/MagicFireballProjectile.cs
  cse3902/Projectiles/ProjectileHandler.cs
  cse3902/Projectiles/SwordProjectile.cs
  cse3902/Rooms/RoomData/RoomEnemies.cs
  cse3902/XMLParsing/Level1.xml
Labels: additional function, bug, code improvement

#353 Small changes
  cse3902/Entities/Enemies/Keese.cs
  cse3902/ParticleSystem/ParticleEngine.cs
Labels: project task
