Repository Jkim-Hack/cse3902, pull requests merged in 2021-03, with the labels that each got.

#114 Fix Keese frame bug
  cse3902/Entities/Enemies/Keese.cs
  cse3902/Entities/KeeseStateMachine.cs
  cse3902/Sprites/EnemySprites/KeeseSprite.cs
Labels: bug

#116 Change Keese movement
  cse3902/Entities/Enemies/Keese.cs
  cse3902/Sprites/EnemySprites/KeeseSprite.cs
Labels: enhancement

#124 Fix enemy random movement
  cse3902/Entities/Enemies/Aquamentus.cs
  cse3902/Entities/Enemies/Gel.cs
  cse3902/Entities/Enemies/Goriya.cs
  cse3902/Entities/Enemies/Keese.cs
  cse3902/Entities/Enemies/Stalfos.cs
  cse3902/Entities/Enemies/Trap.cs
  cse3902/Entities/Enemies/WallMaster.cs
  cse3902/Entities/LinkStateMachine.cs
Labels: bug

#162 Fireball bug fix
  cse3902/Content/fireball.png
  cse3902/Entities/AquamentusStateMachine.cs
  cse3902/Entities/Enemies/Aquamentus.cs
Labels: bug

#166 Damage disabler
  cse3902/Collision/Collidables/BlockCollidable.cs
  cse3902/Collision/Collidables/DoorCollidable.cs
  cse3902/Collision/Collidables/EnemyCollidable.cs
  cse3902/Collision/Collidables/ItemCollidable.cs
  cse3902/Collision/Collidables/PlayerCollidable.cs
  cse3902/Collision/Collidables/ProjectileCollidable.cs
  cse3902/Collision/Collidables/SwordCollidable.cs
  cse3902/Collision/Collidables/WallCollidable.cs
  cse3902/Collision/ICollidable.cs
  cse3902/Constants/DamageConstants.cs
  cse3902/Entities/Enemies/Aquamentus.cs
  cse3902/Entities/Enemies/Gel.cs
  cse3902/Entities/Enemies/Goriya.cs
  cse3902/Entities/Enemies/Keese.cs
  cse3902/Entities/Enemies/Stalfos.cs
  cse3902/Entities/Enemies/WallMaster.cs
  cse3902/Entities/Link.cs
  cse3902/Sprites/EnemySprites/AquamentusSprite.cs
  cse3902/Sprites/LinkSprite.cs
  cse3902/cse3902.csproj
Labels: bug

#167 Boomerang fix
  cse3902/Entities/LinkStateMachine.cs
  cse3902/Projectiles/BoomerangItem.cs
  cse3902/Projectiles/ProjectileHandler.cs
  cse3902/SpriteFactory/ItemSpriteFactory.cs
Labels: bug, code improvement

#168 Camerapausestuff
  cse3902/Commands/ChangeRoomXYCommand.cs
  cse3902/Commands/ChangeRoomZCommand.cs
  cse3902/Commands/CommandList.cs
  cse3902/Commands/DamageLinkCommand.cs
  cse3902/Commands/LinkChangeWeapon.cs
  cse3902/Commands/LinkMovementCommand.cs
  cse3902/Commands/LinkSwordAttackCommand.cs
  cse3902/Commands/LinkUseItemCommand.cs
  cse3902/Commands/PauseCommand.cs
  cse3902/Game1.cs
  cse3902/Rooms/Camera.cs
  cse3902/Rooms/RoomHandler.cs
  cse3902/Rooms/RoomTransitionManager.cs
  cse3902/Sprites/LinkSprite.cs
  cse3902/XMLParsing/BlockParser.cs
  cse3902/XMLParsing/Room1.xml
Labels: project task

#169 Fix infinite damage mask for Aquamentus
  cse3902/Constants/DamageConstants.cs
  cse3902/Entities/Enemies/Aquamentus.cs
Labels: bug

#173 Add projectile collision animation for arrows and swords
  cse3902/Content/Content.mgcb
  cse3902/Content/colorpoof.png
  cse3902/Content/poof.png
  cse3902/Interfaces/IProjectile.cs
  cse3902/Projectiles/ArrowItem.cs
  cse3902/Projectiles/BombItem.cs
  cse3902/Projectiles/BoomerangItem.cs
  cse3902/Projectiles/Fireball.cs
  cse3902/Projectiles/PoofSprite.cs
  cse3902/Projectiles/ProjectileHandler.cs
  cse3902/Projectiles/SwordProjectile.cs
  cse3902/Projectiles/SwordWeapon.cs
  cse3902/Rooms/RoomProjectiles.cs
  cse3902/SpriteFactory/ItemSpriteFactory.cs
Labels: project task

#192 Camerapausestuff
  cse3902/Commands/CommandList.cs
  cse3902/Commands/PauseCommand.cs
  cse3902/Constants/DamageConstants.cs
  cse3902/Constants/DimensionConstants.cs
  cse3902/Game1.cs
  cse3902/NPCs/OldManNPC.cs
  cse3902/Rooms/Camera.cs
  cse3902/Rooms/CameraPart.cs
  cse3902/Rooms/RoomTransitionManager.cs
  cse3902/XMLParsing/NPCParser.cs
  cse3902/XMLParsing/Room1.xml
Labels: bug, code improvement

#196 Camerapausestuff
  cse3902/Blocks/MovementBlock.cs
  cse3902/Blocks/NormalBlock.cs
  cse3902/Blocks/WalkableBlock.cs
  cse3902/Collision/Collidables/BlockCollidable.cs
  cse3902/Collision/Collidables/DoorCollidable.cs
  cse3902/Doors/DownStaircaseDoor.cs
  cse3902/Doors/NormalDownDoor.cs
  cse3902/Doors/NormalLeftDoor.cs
  cse3902/Doors/NormalRightDoor.cs
  cse3902/Doors/NormalUpDoor.cs
  cse3902/Doors/OffscreenUpDoor.cs
  cse3902/Game1.cs
  cse3902/Interfaces/IBlock.cs
  cse3902/Interfaces/ICondition.cs
  cse3902/Interfaces/IDoor.cs
  cse3902/Rooms/Conditions/AllBlocksPushedOpenDoor.cs
  cse3902/Rooms/Conditions/AllEnemiesKilledDropKey.cs
  cse3902/Rooms/Conditions/AllEnemiesKilledOpenDoor.cs
  cse3902/Rooms/Room.cs
  cse3902/Rooms/RoomData/RoomBackground.cs
  cse3902/Rooms/RoomData/RoomBlocks.cs
  cse3902/Rooms/RoomData/RoomConditions.cs
  cse3902/Rooms/RoomData/RoomDoors.cs
  cse3902/Rooms/RoomData/RoomEnemies.cs
  cse3902/Rooms/RoomData/RoomItems.cs
  cse3902/Rooms/RoomData/RoomNPCs.cs
  cse3902/Rooms/RoomData/RoomProjectiles.cs
  cse3902/Rooms/RoomHandler.cs
  cse3902/SpriteFactory/DoorSpriteFactory.cs
  cse3902/SpriteFactory/ItemSpriteFactory.cs
  cse3902/Sprites/DoorSprites/NormalDownOpenDoorSprite.cs
  cse3902/Sprites/DoorSprites/NormalLeftOpenDoorSprite.cs
  cse3902/Sprites/DoorSprites/NormalRightOpenDoorSprite.cs
  cse3902/Sprites/DoorSprites/NormalUpOpenDoorSprite.cs
  cse3902/XMLParsing/BlockParser.cs
  cse3902/XMLParsing/ConditionParser.cs
  cse3902/XMLParsing/DoorParser.cs
  cse3902/XMLParsing/Room1.xml
  cse3902/XMLParsing/XMLParser.cs
  cse3902/cse3902.csproj
Labels: bug, code improvement, project task

#200 Camerapausestuff
  cse3902/Blocks/WalkableBlock.cs
  cse3902/Entities/AquamentusStateMachine.cs
  cse3902/Entities/BlockHandler.cs
  cse3902/Entities/Enemies/Aquamentus.cs
  cse3902/Entities/Enemies/Keese.cs
  cse3902/Entities/Link.cs
  cse3902/Entities/WallMasterStateMachine.cs
  cse3902/Rooms/Conditions/AllEnemiesKilledDropItem.cs
  cse3902/Rooms/Conditions/AllEnemiesKilledDropKey.cs
  cse3902/Rooms/RoomData/RoomConditions.cs
  cse3902/SpriteFactory/ItemSpriteFactory.cs
  cse3902/XMLParsing/ConditionParser.cs
  cse3902/XMLParsing/EnemyParser.cs
  cse3902/XMLParsing/ItemParser.cs
  cse3902/XMLParsing/Room1.xml
Labels: bug, code improvement, project task

#201 Minimap HUD item
  cse3902/Constants/MiniMapConstants.cs
  cse3902/Game1.cs
  cse3902/HUD/CompassHUDItem.cs
  cse3902/HUD/HUDManager.cs
  cse3902/HUD/IHUDItem.cs
  cse3902/HUD/MapHUDItem.cs
  cse3902/HUD/MiniMapHUDItem.cs
  cse3902/Rooms/RoomHandler.cs
Labels: project task

#205 Camerapausestuff
  cse3902/Collision/Collidables/DoorCollidable.cs
  cse3902/Commands/ChangeRoomXYCommand.cs
  cse3902/Commands/ChangeRoomZCommand.cs
  cse3902/Commands/CommandList.cs
  cse3902/Commands/LinkChangeWeapon.cs
  cse3902/Commands/LinkMovementCommand.cs
  cse3902/Commands/LinkSwordAttackCommand.cs
  cse3902/Commands/LinkUseItemCommand.cs
  cse3902/Commands/PauseCommand.cs
  cse3902/Constants/DimensionConstants.cs
  cse3902/Constants/MiniMapConstants.cs
  cse3902/Doors/NormalDownDoor.cs
  cse3902/Doors/NormalLeftDoor.cs
  cse3902/Doors/NormalRightDoor.cs
  cse3902/Doors/NormalUpDoor.cs
  cse3902/Game1.cs
  cse3902/GameStateManager.cs
  cse3902/HUD/MiniMapHUDItem.cs
  cse3902/Rooms/Conditions/AllBlocksPushedOpenDoor.cs
  cse3902/Rooms/RoomHandler.cs
  cse3902/XMLParsing/XMLParser.cs
Labels: code improvement, project task

#206 Automatic scaling
  cse3902/Commands/CommandList.cs
  cse3902/Constants/DimensionConstants.cs
  cse3902/Constants/MiniMapConstants.cs
  cse3902/HUD/MiniMapHUDItem.cs
  cse3902/Rooms/Camera.cs
  cse3902/Rooms/CameraPart.cs
Labels: code improvement

#208 bombed door sprite
  cse3902/Commands/LinkMovementCommand.cs
  cse3902/Content/Content.mgcb
  cse3902/Content/black.png
  cse3902/Content/doors.png
  cse3902/Entities/LinkStateMachine.cs
  cse3902/Game1.cs
  cse3902/GameStateManager.cs
  cse3902/Rooms/RoomHandler.cs
  cse3902/Rooms/RoomTransitionManager.cs
  cse3902/SpriteFactory/DoorSpriteFactory.cs
  cse3902/Sprites/DoorSprites/NormalDownOpenDoorSprite.cs
  cse3902/Sprites/DoorSprites/NormalLeftOpenDoorSprite.cs
  cse3902/Sprites/DoorSprites/NormalRightOpenDoorSprite.cs
  cse3902/Sprites/DoorSprites/NormalUpOpenDoorSprite.cs
  cse3902/Sprites/SpriteUtilities.cs
Labels: project task

#212 Add HealthHUDItem and HeartSprites for the HUD Item
  cse3902/Constants/HUDPositionConstants.cs
  cse3902/Constants/HeartConstants.cs
  cse3902/Content/.Content.mgcb.swp
  cse3902/Content/Content.mgcb
  cse3902/Content/UI/HealthUI.png
  cse3902/Content/UI/HeartsUI.png
  cse3902/HUD/HUDItems/HealthHUDItem.cs
  cse3902/HUD/HUDManager.cs
  cse3902/SpriteFactory/HUDSpriteFactory.cs
  cse3902/Sprites/HUD/HeartHUDSprite.cs
  cse3902/cse3902.csproj
Labels: project task

#222 HUD manager & minimap
  cse3902/Constants/MiniMapConstants.cs
  cse3902/Content/Content.mgcb
  cse3902/Content/UI/level1.png
  cse3902/Game1.cs
  cse3902/HUD/HUDItems/CompassHUDItem.cs
  cse3902/HUD/HUDItems/MapHUDItem.cs
  cse3902/HUD/HUDItems/MiniMapHUDItem.cs
  cse3902/HUD/HUDManager.cs
  cse3902/SpriteFactory/HUDSpriteFactory.cs
  cse3902/Utilities/HUDUtilities.cs
  cse3902/cse3902.csproj
Labels: code improvement, project task
